---
bucket: cu-test
log-key: logs
push-queue: cu-pushes
build-queue: cu-builds
pipeline:
  test-web-app-units:
    script: "true"
    repo: &web-repo https://github.com/camelpunch/cu-example-web-app
  test-web-app-integrations:
    script: "true"
    repo: *web-repo
  downstream: # downstream of two jobs that run in parallel
    deploy-web-app:
      script: "true"
      repo: *web-repo
    announce-web-deployment:
      script: "pwd"
      repo: *web-repo
    downstream:
      test-ios-client-against-web-app:
        script: "ls"
        repo: &ios-repo https://github.com/camelpunch/cu-example-ios-app
